import type { Mode } from './config';
import { NEUTRAL_STEPS, SCALE_STEPS } from './color';
import { TYPE_SCALE } from './type';
import type { Theme, Vars } from './theme';

const HEADER = '/* Generated by UI System. Edit ui.config.json and run `ui-system build`, never this file. */';

const block = (selector: string, vars: Vars) =>
  `${selector} {\n${Object.entries(vars).map(([k, v]) => `  ${k}: ${v};`).join('\n')}\n}`;

const prefixed = (vars: Vars) => Object.fromEntries(Object.entries(vars).map(([k, v]) => [`--uis-${k}`, v]));

export interface CSSOptions {
  /** Where the default-mode variables go. */
  selector?: string;
  /** Include the Google Fonts @import line. */
  fonts?: boolean;
  /** Also follow the OS color scheme when no data-uis-mode is set. */
  system?: boolean;
}

/** Plain CSS variables for any stack: plain HTML, Framer, Shopify, Next.js. */
export function toCSS(theme: Theme, opts: CSSOptions = {}): string {
  const { selector = ':root', fonts = true, system = false } = opts;
  const mode: Mode = theme.config.color.mode;
  const other: Mode = mode === 'light' ? 'dark' : 'light';
  const base = theme.vars(mode);
  const parts = [HEADER];
  if (fonts) parts.push(`@import url('${theme.fontsUrl}');`);
  parts.push(block(selector, base));
  parts.push(block(`[data-uis-mode="${other}"]${other === 'dark' ? ', .dark' : ', .light'}`, prefixed(theme.colors[other])));
  parts.push(block(`[data-uis-mode="${mode}"]${mode === 'dark' ? ', .dark' : ', .light'}`, prefixed(theme.colors[mode])));
  if (system && mode === 'light') {
    parts.push(`@media (prefers-color-scheme: dark) {\n${block(`  ${selector}:not([data-uis-mode="light"]):not(.light)`, prefixed(theme.colors.dark))}\n}`);
  }
  return parts.join('\n\n') + '\n';
}

const SEMANTIC = [
  'bg', 'surface', 'surface-2', 'surface-3', 'line', 'line-strong', 'ink', 'ink-2', 'ink-3', 'inverse', 'inverse-ink', 'on-image', 'focus',
  ...['primary', 'accent', 'success', 'warning', 'danger', 'info'].flatMap((r) => [r, `${r}-hover`, `${r}-ink`, `${r}-soft`, `${r}-soft-ink`, `${r}-text`]),
];

/**
 * Tailwind v4 theme. It maps utilities to the runtime variables, so
 * `bg-primary rounded-control font-display shadow-float` follow whatever
 * theme is active, including live changes and dark mode.
 */
export function toTailwind(): string {
  const lines: string[] = [];
  for (const name of SEMANTIC) lines.push(`  --color-${name}: var(--uis-${name});`);
  for (const r of ['primary', 'accent', 'success', 'warning', 'danger', 'info']) {
    for (const s of SCALE_STEPS) lines.push(`  --color-${r}-${s}: var(--uis-${r}-${s});`);
  }
  for (const s of NEUTRAL_STEPS) lines.push(`  --color-neutral-${s}: var(--uis-neutral-${s});`);
  for (const r of ['chip', 'control', 'field', 'card', 'panel', 'media', 'shell', 'avatar']) lines.push(`  --radius-${r}: var(--uis-r-${r});`);
  lines.push('  --font-display: var(--uis-font-display);', '  --font-sans: var(--uis-font-body);', '  --font-mono: var(--uis-font-mono);');
  for (const s of ['sm', 'md', 'lg', 'float']) lines.push(`  --shadow-${s}: var(--uis-shadow-${s});`);
  lines.push('  --ease-out-soft: var(--uis-ease-out);', '  --ease-in-out-soft: var(--uis-ease-in-out);');
  for (const s of ['sm', 'md', 'lg']) lines.push(`  --spacing-control-${s}: var(--uis-h-${s});`);
  return `${HEADER}\n/* Import after tailwindcss and theme.css:  @import "tailwindcss"; @import "./theme.css"; @import "./tailwind.css"; */\n\n@theme inline {\n${lines.join('\n')}\n}\n\n@custom-variant dark (&:where([data-uis-mode="dark"], [data-uis-mode="dark"] *, .dark, .dark *));\n`;
}

const USAGE: Record<string, string> = {
  bg: 'Page background.',
  surface: 'Cards, panels, inputs, sheets.',
  'surface-2': 'Subtle fills: table headers, sidebars, sunken wells.',
  'surface-3': 'Hover fill for rows, nav items and ghost buttons.',
  line: 'Hairline borders and dividers.',
  'line-strong': 'Input borders and stronger dividers.',
  ink: 'Primary text on bg and surface.',
  'ink-2': 'Secondary text: descriptions, table cells.',
  'ink-3': 'Tertiary text: captions, placeholders, meta. Still passes 4.5:1.',
  inverse: 'Inverted surfaces: tooltips, toasts.',
  'inverse-ink': 'Text on inverse.',
  'on-image': 'Text over photography, always paired with image-scrim.',
  scrim: 'Backdrop behind drawers and dialogs.',
  focus: 'Focus outline color.',
  'float-bg': 'Floating navs, docks and popovers (solid or glass).',
  'float-border': 'Border of floating elements.',
  'card-border': 'Card and panel border (transparent when borders are off).',
};
const roleUsage = (r: string): Record<string, string> => ({
  [r]: `${r[0].toUpperCase() + r.slice(1)} fills: ${r === 'primary' ? 'primary buttons, active nav items, selected states' : r === 'accent' ? 'highlights, badges, focus, charts' : `${r} icons, badges and banners`}. The exact brand hex in light mode.`,
  [`${r}-hover`]: `Hover and pressed state of ${r}.`,
  [`${r}-ink`]: `Text and icons on ${r} fills (auto black or white by contrast).`,
  [`${r}-soft`]: `Tinted background for ${r} badges, alerts and selected rows.`,
  [`${r}-soft-ink`]: `Text on ${r}-soft (4.5:1).`,
  [`${r}-text`]: `${r} used as text or links on bg (4.5:1).`,
});
for (const r of ['primary', 'accent', 'success', 'warning', 'danger', 'info']) Object.assign(USAGE, roleUsage(r));

const RADIUS_USAGE: Record<string, string> = {
  chip: 'Badges, tags, chips.',
  control: 'Buttons, nav items, tabs, segmented controls.',
  field: 'Inputs, selects, search fields.',
  card: 'Cards and tiles.',
  panel: 'Popovers, drawers, dialogs, inset app panels.',
  media: 'Images, video, thumbnails.',
  shell: 'Floating nav bars, docks and islands.',
  inner: 'Content nested inside a panel (panel minus 8px padding).',
};

/**
 * Claude Design System tokens.json: lists of {name, value, usage}, colors
 * with a light and a dark theme. Only hex and rgba values, so every token
 * survives the importer.
 */
export function toDesignTokens(theme: Theme) {
  const mode = theme.config.color.mode;
  const other: Mode = mode === 'light' ? 'dark' : 'light';
  const themes = [
    { id: mode, name: mode === 'light' ? 'Light' : 'Dark' },
    { id: other, name: other === 'light' ? 'Light' : 'Dark' },
  ];
  const colorTokens: { name: string; value: Record<string, string>; usage: string }[] = [];
  const keys = Object.keys(theme.colors.light).filter((k) => !k.startsWith('shadow') && k !== 'image-scrim' && k !== 'focus-ring');
  for (const k of keys) {
    const fix = (v: string) => (v === 'transparent' ? '#00000000' : v);
    colorTokens.push({ name: k, value: { [mode]: fix(theme.colors[mode][k]), [other]: fix(theme.colors[other][k]) }, usage: USAGE[k] ?? '' });
  }
  for (const [name, scale] of Object.entries(theme.scales)) {
    for (const [step, hex] of Object.entries(scale)) {
      if (step === 'anchor') continue;
      colorTokens.push({ name: `${name}-${step}`, value: { [mode]: hex as string }, usage: `${name} scale, step ${step}.` });
    }
  }
  const t = theme.type;
  const groups = [
    {
      name: 'Display', family: 'display',
      styles: (['display-2xl', 'display-xl', 'display-l', 'display-m'] as const).map((k) => {
        const [size, lh] = TYPE_SCALE[k];
        return { name: k, fontSize: `${size}px`, lineHeight: `${Math.round(size * lh)}px`, fontWeight: t.displayWeight, letterSpacing: t.displayTracking };
      }),
    },
    {
      name: 'Text', family: 'body',
      styles: (['h1', 'h2', 'h3', 'body-l', 'body', 'body-s', 'label', 'caption', 'overline'] as const).map((k) => {
        const [size, lh, w, tr] = TYPE_SCALE[k];
        return { name: k, fontSize: `${size}px`, lineHeight: `${Math.round(size * (lh as number))}px`, fontWeight: w as number, letterSpacing: tr as string };
      }),
    },
    {
      name: 'Code', family: 'mono',
      styles: [{ name: 'code', fontSize: '13px', lineHeight: '20px', fontWeight: 400 }],
    },
  ];
  const r = theme.radius;
  return {
    name: theme.config.name,
    version: 1,
    meta: { source: 'ui-system', config: theme.config },
    color: { themes, tokens: colorTokens },
    type: {
      fonts: [],
      families: { display: t.stacks.display, body: t.stacks.body, mono: t.stacks.mono },
      groups,
    },
    spacing: {
      tokens: [4, 8, 12, 16, 20, 24, 32, 40, 48, 64, 80, 96].map((v, i) => ({ name: `space-${i + 1}`, value: `${v}px`, usage: i < 3 ? 'Inside controls and tight groups.' : i < 7 ? 'Card padding and gaps between related blocks.' : 'Section spacing.' }))
        .concat([
          { name: 'control-sm', value: theme.shared['h-sm'], usage: 'Small control height.' },
          { name: 'control-md', value: theme.shared['h-md'], usage: 'Default control height (touch target).' },
          { name: 'control-lg', value: theme.shared['h-lg'], usage: 'Large control height, hero CTAs.' },
        ]),
    },
    radius: {
      tokens: (['chip', 'control', 'field', 'card', 'panel', 'media', 'shell', 'inner'] as const).map((k) => ({
        name: `radius-${k}`,
        value: `${Math.min(r[k] as number, 999)}px`,
        usage: RADIUS_USAGE[k],
      })),
    },
    shadow: {
      tokens: ['sm', 'md', 'lg', 'float'].map((s) => ({ name: `shadow-${s}`, value: theme.colors[mode][`shadow-${s}`], usage: s === 'float' ? 'Floating navs and docks.' : s === 'lg' ? 'Drawers, dialogs, popovers.' : s === 'md' ? 'Raised cards, menus.' : 'Resting cards, inputs.' })),
    },
  };
}

/** Resolved values as plain JSON (useful for Framer variables or native apps). */
export function toJSON(theme: Theme) {
  return {
    name: theme.config.name,
    config: theme.config,
    fontsUrl: theme.fontsUrl,
    light: theme.vars('light'),
    dark: theme.vars('dark'),
  };
}
